<Project>
    <PropertyGroup>
        <!-- Modify this file and change it to Directory.Build.props -->
        <!-- LimbusCompanyFolder should be where your LimbusCompany.exe lives -->
        <LimbusCompanyFolder>C:/Users/Admin/Downloads/LetheLauncher-Distribution-7/</LimbusCompanyFolder>
    </PropertyGroup>
</Project>