<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
    <DebugSymbols>true</DebugSymbols>
    <LangVersion>10.0</LangVersion>
    <IsPublishable>True</IsPublishable>
    <TargetFramework>net6.0</TargetFramework>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <OutputPath>.\Release</OutputPath>
    <NoWarn>1701;1702;2211;CA2211;IDE1006;IDE0060</NoWarn>
    <DebugType>none</DebugType>
    <RootNamespace>CustomMirror</RootNamespace>
    <AssemblyName>CustomMirror</AssemblyName>
    <Product>CustomMirror</Product>
    <Version>0.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <!-- ~~~~~ ASSEMBLY REFERENCES ~~~~~ -->
  <!-- BepinEx -->
  <ItemGroup>
    <Reference Include="System.Runtime" />
    <Reference Include="$(LimbusCompanyFolder)\BepInEx\core\*.dll">
      <HintPath>%(Identity)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="$(LimbusCompanyFolder)\BepInEx\interop\*.dll">
      <HintPath>%(Identity)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="$(LimbusCompanyFolder)\mono\Managed\*.dll">
      <HintPath>%(Identity)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lethe">
    <HintPath>$(LimbusCompanyFolder)\BepInEx\plugins\Lethe.dll</HintPath>
    <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Task after build (e.g. copying to game folder, merging, etc.) -->
  <Target Name="CopyFile" AfterTargets="build">
    <Message Text="Copying BIE files..." Importance="high" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFiles="$(LimbusCompanyFolder)\BepInEx\plugins\$(AssemblyName).dll" />
  </Target>
</Project>
